from insert_interval_use_sort import Solution


def test_insert():
    intervals = [[1, 3], [6, 9]]
    new_interval = [2, 5]
    assert Solution().insert(intervals, new_interval) == [[1, 5], [6, 9]]
    intervals = [[1, 2], [3, 5], [6, 7], [8, 10], [12, 16]]
    new_interval = [4, 8]
    assert Solution().insert(intervals, new_interval) == [[1, 2], [3, 10], [12, 16]]
    intervals = []
    new_interval = [5, 7]
    assert Solution().insert(intervals, new_interval) == [[5, 7]]
    intervals = [[1, 5]]
    new_interval = [2, 3]
    assert Solution().insert(intervals, new_interval) == [[1, 5]]
    intervals = [[1, 5]]
    new_interval = [2, 7]
    assert Solution().insert(intervals, new_interval) == [[1, 7]]
    intervals = [[1, 5]]
    new_interval = [6, 8]
    assert Solution().insert(intervals, new_interval) == [[1, 5], [6, 8]]
    intervals = [[1, 5], [6, 8]]
    new_interval = [5, 6]
    assert Solution().insert(intervals, new_interval) == [[1, 8]]
