#!/bin/bash

# install_aliases.sh - Install developer aliases
# ==============================================

alias le="set -o allexport; source .env; set +o allexport"

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_message() {
    echo -e "${1}${2}${NC}"
}

print_message $BLUE "🚀 Developer Aliases Installer"
print_message $BLUE "=============================="

# Detect shell
SHELL_RC=""
if [[ "$SHELL" == *"zsh"* ]]; then
    SHELL_RC="$HOME/.zshrc"
    SHELL_NAME="zsh"
elif [[ "$SHELL" == *"bash"* ]]; then
    if [[ -f "$HOME/.bashrc" ]]; then
        SHELL_RC="$HOME/.bashrc"
    else
        SHELL_RC="$HOME/.bash_profile"
    fi
    SHELL_NAME="bash"
elif [[ "$SHELL" == *"fish"* ]]; then
    SHELL_RC="$HOME/.config/fish/config.fish"
    SHELL_NAME="fish"
else
    print_message $YELLOW "⚠️  Unknown shell, defaulting to ~/.bashrc"
    SHELL_RC="$HOME/.bashrc"
    SHELL_NAME="bash"
fi

print_message $GREEN "✅ Detected shell: $SHELL_NAME"
print_message $BLUE "📝 Will install to: $SHELL_RC"

# Check if aliases file exists
ALIASES_FILE="$HOME/.dev_aliases"

if [[ -f "$ALIASES_FILE" ]]; then
    print_message $YELLOW "⚠️  Aliases file already exists at $ALIASES_FILE"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_message $BLUE "ℹ️  Installation cancelled"
        exit 0
    fi
fi

# Create aliases file
print_message $BLUE "📝 Creating aliases file..."

cat > "$ALIASES_FILE" << 'EOF'
# Developer Aliases Collection
# ============================
# Auto-generated by install_aliases.sh

# ==========================================
# GIT ALIASES
# ==========================================

# Basic Git Operations
alias g='git'
alias ga='git add'
alias gaa='git add .'
alias gap='git add -p'
alias gb='git branch'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit -a'
alias gcam='git commit -am'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout main'
alias gcos='git checkout staging'
alias gcod='git checkout develop'

# Git Status and Logs
alias gs='git status'
alias gss='git status -s'
alias gl='git log'
alias glo='git log --oneline'
alias glg='git log --graph --oneline --decorate --all'
alias gll='git log --graph --pretty=format:"%C(yellow)%h%Creset -%C(red)%d%Creset %s %C(green)(%cr) %C(cyan)<%an>%Creset" --abbrev-commit --all'

# Git Push/Pull/Fetch
alias gp='git push'
alias gpu='git push -u origin'
alias gpf='git push --force-with-lease'
alias gpl='git pull'
alias gf='git fetch'
alias gfa='git fetch --all'

# Git Merge/Rebase
alias gm='git merge'
alias gr='git rebase'
alias gri='git rebase -i'
alias grc='git rebase --continue'
alias gra='git rebase --abort'

# Git Diff and Show
alias gd='git diff'
alias gdc='git diff --cached'
alias gdh='git diff HEAD'
alias gshow='git show'

# Git Stash
alias gst='git stash'
alias gstp='git stash pop'
alias gstl='git stash list'
alias gstd='git stash drop'

# Git Remote
alias grem='git remote'
alias gremv='git remote -v'
alias grema='git remote add'
alias gremd='git remote remove'

# Git Reset and Clean
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias gclean='git clean -fd'
alias gunstage='git reset HEAD --'

# Git Shortcuts
alias gwip='git add . && git commit -m "WIP"'
alias gunwip='git log -n 1 | grep -q -c "WIP" && git reset HEAD~1'
alias gignore='git update-index --assume-unchanged'
alias gunignore='git update-index --no-assume-unchanged'

# ==========================================
# KUBERNETES (K8S) ALIASES
# ==========================================

# Basic kubectl
alias k='kubectl'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias kgd='kubectl get deployments'
alias kgn='kubectl get nodes'
alias kga='kubectl get all'
alias kgns='kubectl get namespaces'

# Kubectl with wide output
alias kgpw='kubectl get pods -o wide'
alias kgsw='kubectl get services -o wide'
alias kgdw='kubectl get deployments -o wide'
alias kgnw='kubectl get nodes -o wide'

# Kubectl describe
alias kdp='kubectl describe pod'
alias kds='kubectl describe service'
alias kdd='kubectl describe deployment'
alias kdn='kubectl describe node'

# Kubectl logs
alias kl='kubectl logs'
alias klf='kubectl logs -f'
alias klp='kubectl logs -p'

# Kubectl exec
alias kex='kubectl exec -it'
alias ksh='kubectl exec -it'

# Kubectl apply/delete
alias ka='kubectl apply -f'
alias kdel='kubectl delete'
alias kdelf='kubectl delete -f'

# Kubectl port forwarding
alias kpf='kubectl port-forward'

# Kubectl context and namespace
alias kcc='kubectl config current-context'
alias kcg='kubectl config get-contexts'
alias kcs='kubectl config use-context'
alias kns='kubectl config set-context --current --namespace'

# Kubectl top
alias ktop='kubectl top'
alias ktop-nodes='kubectl top nodes'
alias ktop-pods='kubectl top pods'

# Useful combinations
alias kgpa='kubectl get pods --all-namespaces'
alias kgsa='kubectl get services --all-namespaces'
alias kgda='kubectl get deployments --all-namespaces'

# ==========================================
# DOCKER ALIASES
# ==========================================

# Basic Docker commands
alias d='docker'
alias dp='docker ps'
alias dpa='docker ps -a'
alias di='docker images'
alias dil='docker image ls'

# Docker run
alias dr='docker run'
alias drit='docker run -it'
alias drm='docker run --rm'
alias drmit='docker run --rm -it'

# Docker build
alias db='docker build'
alias dbt='docker build -t'

# Docker exec
alias dex='docker exec'
alias deit='docker exec -it'

# Docker logs
alias dl='docker logs'
alias dlf='docker logs -f'
alias dlt='docker logs --tail'

# Docker stop/start/restart
alias dst='docker stop'
alias dsta='docker start'
alias dre='docker restart'

# Docker remove
alias drm-container='docker rm'
alias drm-image='docker rmi'
alias drmf='docker rm -f'

# Docker system
alias dsp='docker system prune'
alias dspf='docker system prune -f'
alias dspa='docker system prune -a'
alias ddf='docker system df'

# Docker compose
alias dc='docker-compose'
alias dcu='docker-compose up'
alias dcud='docker-compose up -d'
alias dcd='docker-compose down'
alias dcb='docker-compose build'
alias dcl='docker-compose logs'
alias dclf='docker-compose logs -f'
alias dcp='docker-compose ps'
alias dcr='docker-compose restart'
alias dce='docker-compose exec'

# Docker volume
alias dv='docker volume'
alias dvl='docker volume ls'
alias dvp='docker volume prune'

# Docker network
alias dn='docker network'
alias dnl='docker network ls'
alias dnp='docker network prune'

# Useful Docker combinations
alias dcleanup='docker system prune -a --volumes'
alias dstop-all='docker stop $(docker ps -q)'
alias drm-all='docker rm $(docker ps -aq)'
alias drmi-dangling='docker rmi $(docker images -f "dangling=true" -q)'

# ==========================================
# GOLANG ALIASES
# ==========================================

# Basic Go commands
alias go-build='go build'
alias go-run='go run'
alias go-test='go test'
alias go-fmt='go fmt'
alias go-vet='go vet'
alias go-mod='go mod'

# Go build variations
alias gob='go build'
alias gobr='go build -race'
alias gocb='go build -o'

# Go run
alias gor='go run'
alias gorr='go run -race'

# Go test
alias got='go test'
alias gotv='go test -v'
alias gotc='go test -cover'
alias gotb='go test -bench=.'
alias gotr='go test -race'

# Go modules
alias gomi='go mod init'
alias gomt='go mod tidy'
alias gomv='go mod verify'
alias gomd='go mod download'

# Go get
alias gog='go get'
alias gogu='go get -u'

# Go format and lint
alias gof='go fmt ./...'
alias gov='go vet ./...'

# Go install
alias goi='go install'

# Go clean
alias gocl='go clean'
alias goclc='go clean -cache'
alias goclt='go clean -testcache'

# Go generate
alias gogen='go generate'

# Useful Go combinations
alias go-check='go fmt ./... && go vet ./... && go test ./...'
alias go-build-all='GOOS=linux go build && GOOS=windows go build && GOOS=darwin go build'

# ==========================================
# GENERAL PRODUCTIVITY ALIASES
# ==========================================

# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'
alias -- -='cd -'

# List commands
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ls -altr'
alias lh='ls -alh'

# Common commands
alias c='clear'
alias h='history'
alias j='jobs'
alias v='vim'
alias nv='nvim'

# Process management
alias psg='ps aux | grep'

# Network
alias ports='netstat -tulanp'
alias myip='curl -s https://httpbin.org/ip | jq -r .origin'

# File operations
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias mkdir='mkdir -p'

# ==========================================
# USEFUL FUNCTIONS
# ==========================================

# Git function to create and push new branch
gnb() {
    git checkout -b "$1" && git push -u origin "$1"
}

# Docker function to remove containers by pattern
drm-pattern() {
    docker rm $(docker ps -a | grep "$1" | awk '{print $1}')
}

# Kubernetes function to get pod logs by pattern
kl-pattern() {
    kubectl logs $(kubectl get pods | grep "$1" | awk '{print $1}') -f
}

# Go function to create new module
go-new() {
    mkdir "$1" && cd "$1" && go mod init "$1"
}

# Function to show all aliases
show-aliases() {
    echo "=== GIT ALIASES ==="
    alias | grep '^g[a-z]'
    echo -e "\n=== KUBERNETES ALIASES ==="
    alias | grep '^k[a-z]'
    echo -e "\n=== DOCKER ALIASES ==="
    alias | grep '^d[a-z]'
    echo -e "\n=== GOLANG ALIASES ==="
    alias | grep '^go[a-z]'
}

EOF

print_message $GREEN "✅ Aliases file created at $ALIASES_FILE"

# Add source command to shell config
SOURCE_LINE="source $ALIASES_FILE"

if ! grep -q "source.*\.dev_aliases" "$SHELL_RC" 2>/dev/null; then
    print_message $BLUE "📝 Adding aliases to $SHELL_RC"
    echo "" >> "$SHELL_RC"
    echo "# Developer aliases" >> "$SHELL_RC"
    echo "$SOURCE_LINE" >> "$SHELL_RC"
    print_message $GREEN "✅ Added to $SHELL_RC"
else
    print_message $YELLOW "⚠️  Aliases already sourced in $SHELL_RC"
fi

# Source the aliases for current session
source "$ALIASES_FILE"

print_message $GREEN "🎉 Installation complete!"
print_message $BLUE "📋 Available alias categories:"
print_message $NC "  • Git: g, ga, gc, gp, etc."
print_message $NC "  • Kubernetes: k, kgp, kgs, etc."
print_message $NC "  • Docker: d, dp, dc, etc."
print_message $NC "  • Go: gor, got, gob, etc."

print_message $YELLOW "💡 Tips:"
print_message $NC "  • Run 'show-aliases' to see all aliases"
print_message $NC "  • Restart your terminal or run: source $SHELL_RC"
print_message $NC "  • Edit $ALIASES_FILE to customize"

print_message $BLUE "🚀 Quick test commands:"
print_message $NC "  gs          # git status"
print_message $NC "  k get pods  # kubectl get pods"
print_message $NC "  dp          # docker ps"
print_message $NC "  gor main.go # go run main.go"
